# PR Risk Classification Configuration
# Automatically classifies PRs into Express Lane, Standard, or High-Risk

express_lane:
  # Low-risk changes that can be fast-tracked
  paths:
    - "docs/**"
    - "*.md"
    - "**/*.properties"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/test/**"
    - "**/*.json"
    - ".github/**"
  size_limit: 50  # Max lines changed
  auto_merge: true  # Can self-merge after CI passes

standard:
  # Normal development workflow
  paths:
    - "base/**"
    - "genefunk/**"
    - "data/**"
    - "api/**"
    - "character-generator-starter/**"
    - "data-starter/**"
    - "genefunk-starter/**"
  exclude:
    - "**/SecurityConfiguration.kt"
    - "**/SecurityConfig.kt"
    - "**/AuthController.kt"
    - "**/AuthenticationController.kt"
  size_limit: 500  # Max lines changed

high_risk:
  # Critical changes requiring full review
  paths:
    - "**/security/**"
    - "**/auth/**"
    - "security/**"
    - "security-starter/**"
  keywords:
    - "authentication"
    - "authorization"
    - "password"
    - "token"
    - "deleteById"
    - "deleteAll"
    - "dropTable"
    - "SQL"
    - "executeQuery"
  patterns:
    - ".*SecurityConfiguration.*"
    - ".*AuthController.*"
    - ".*PasswordEncoder.*"

# Workflow assignments
workflows:
  express_lane:
    steps:
      - "Automated checks (lint, build, unit tests)"
      - "Auto-merge after green CI"
      - "Pepper notified (async)"
    sla: "Same day"

  standard:
    steps:
      - "Automated code review"
      - "CI/CD pipeline (build, test, security scan)"
      - "Automated accessibility tests (if UI)"
      - "Automated QA tests"
      - "Pepper async acceptance"
    sla: "2-3 days"

  high_risk:
    steps:
      - "Full manual code review"
      - "Vision manual accessibility review (if UI)"
      - "Bruce comprehensive testing"
      - "Pepper formal acceptance"
      - "Security review"
    sla: "5-7 days"
