logging:
  level:
    com:
      springframework:
        web: DEBUG
        security: DEBUG
        oauth2: DEBUG
        boot: DEBUG
    de:
      hipp:
        pnp:
          auth: debug
          security:
            user: DEBUG  # Add this for UserService, UserRepository, and UserListener
          base:
            rabbitmq: DEBUG  # Add this for UserInfoProducer
          rabbitmq: DEBUG  # Add this for other RabbitMQ components
