systems:
  genefunk:
    books:
      crb:
        backgrounds:
          academic:
            label: "Academic"
            description: "You spent years in university studying your discipline. Books, research, and learning the mysteries of human nature and the universe are your life."
          artist:
            label: "Artist"
            description: "You are a creative spirit, who needs to produce art for an audience."
          ideologue:
            label: "Ideologue"
            description: "You have devoted your life to a specific cause or ideology. You pursue it with religious zeal and view the world through your doctrine’s lens."
          investigator:
            label: "Investigator"
            description: "You uncover hidden truths and solve crimes or mysteries, whether as a private detective, corporate agent, or insurance investigator."
          makeYourOwn:
            label: "Make Your Own"
            description: "You craft a unique background tailored to your character’s story. Work with the GM to define skills, proficiencies, and narrative hooks."
          militaryVeteran:
            label: "Military Veteran"
            description: "You spent years in a military operation, seeing battle and bloodshed. Your training and discipline make you a lethal killer."
          outlaw:
            label: "Outlaw"
            description: "You made your living on the wrong side of the law, mastering theft, fraud, and violence to survive and profit."
          religiousDisciple:
            label: "Religious Disciple"
            description: "You follow a faith or doctrine with unwavering devotion, wielding holy texts or dogma to guide your actions."
          slumDog:
            label: "Slum Dog"
            description: "You grew up in the undercity, scraping by on the streets and honing your wits to survive in poverty and danger."
          stargazer:
            label: "Stargazer"
            description: "You spent nights studying the sky, becoming an expert in navigation, astrology, or the mysteries of the cosmos."
          technician:
            label: "Technician"
            description: "You’re a hands-on expert in machines and electronics, skilled at repairing daemons, jury-rigging devices, and hacking hardware."
          trustFundKid:
            label: "Trust Fund Kid"
            description: "You grew up wealthy, enjoying every comfort and privilege. You may lack street smarts but have resources at your disposal."

        classes:
          biohacker:
            label: "Biohacker"
            description: "Masters of biological manipulation, using bioware and genetic tweaks to shape the battlefield."
          codehacker:
            label: "Codehacker"
            description: "Experts of digital warfare and intrusion, able to hack daemons and security systems."
          crook:
            label: "Crook"
            description: "Streetwise criminals who use stealth, charm, and violence to get what they want."
          engineer:
            label: "Engineer"
            description: "Innovators and builders, adept at crafting gadgets, vehicles, and mechanical allies."
          gunfighter:
            label: "Gunfighter"
            description: "Deadly with firearms, trained to handle all manner of ranged and close-quarters weaponry."
          hardcase:
            label: "Hardcase"
            description: "Tough front-line fighters who absorb damage and protect their allies."
          puppeteer:
            label: "Puppeteer"
            description: "Controllers of daemons and machines, twisting technology to do their bidding."
          samurai:
            label: "Samurai"
            description: "Elite mercenaries trained in a code of honor, blending martial skill with corporate loyalty."
          suit:
            label: "Suit"
            description: "Corporate operatives and negotiators who wield power through influence."
          traceur:
            label: "Traceur"
            description: "Extreme stunt performers and athletes, blending acrobatics with showmanship."

        features:
          acuteOlfaction:
            label: "Acute Olfaction"
            description: "You have countless folds in your nose for increased surface area. You can track and identify scents in great detail, granting advantage on smell-based Perception checks."
          acuteSenses:
            label: "Acute Senses"
            description: "Your peripheral vision and other senses are heightened, granting darkvision and advantage on initiative rolls."
          actionStarBrain:
            label: "Action Star Brain"
            description: "Your Intelligence and Wisdom scores are decreased by 2."
          adrenalineSurge:
            label: "Adrenaline Surge"
            description: "When you take damage, you can use your reaction to gain temporary hit points equal to your proficiency bonus."
          albinism:
            label: "Albinism"
            description: "Your lack of melanin makes your skin and hair fragile to sunlight, and you have disadvantage on Charisma (Intimidation) checks."
          amphibious:
            label: "Amphibious"
            description: "You can breathe underwater and have a swim speed equal to your walking speed."
          animalRage:
            label: "Animal Rage"
            description: "You can enter a feral rage, gaining bonus damage and resistance for a short time."
          athleticPhenom:
            label: "Athletic Phenom"
            description: "Your genes have been tweaked for optimal athletic expression, granting benefits to movement and Acrobatics checks."
          bioluminescence:
            label: "Bioluminescence"
            description: "Your skin glows with blue-green light. You suffer disadvantage on Stealth checks unless completely covered."
          blindLoyalty:
            label: "Blind Loyalty"
            description: "You have absolute devotion to your pack and will put yourself in harm’s way to protect them."
          camouflage:
            label: "Camouflage"
            description: "You can blend into natural environments, gaining advantage on Stealth checks when in terrain you’re adapted to."
          carnivore:
            label: "Carnivore"
            description: "You must eat raw meat to sustain yourself and have advantage on tracking by scent."
          chemicalDependence:
            label: "Chemical Dependence"
            description: "In addition to regular food, you must consume a daily nutrient supplement called Median. Failure counts as not eating and can be problematic during long missions."
          claws:
            label: "Claws"
            description: "You possess natural claws that deal slashing damage as a weapon."
          coldResistance:
            label: "Cold Resistance"
            description: "You have resistance to cold damage."
          colossalPresence:
            label: "Colossal Presence"
            description: "Your immense size intimidates foes, granting advantage on Intimidation checks."
          contact:
            label: "Contact"
            description: "You have a reliable ally in the underworld or military who can assist you once per session."
          crocodilianForm:
            label: "Crocodilian Form"
            description: "Your scaly hide grants you a bonus to AC and advantage on grapple saves."
          darkvision:
            label: "Darkvision"
            description: "You can see in dim light within 18 meters as if it were bright light, and in darkness as if it were dim light."
          dangerSense:
            label: "Danger Sense"
            description: "You gain a bonus to initiative and cannot be surprised while conscious."
          emotionallyIntuitive:
            label: "Emotionally Intuitive"
            description: "You can read emotional states with uncanny accuracy, gaining advantage on Insight checks."
          enchanting:
            label: "Enchanting"
            description: "You gain proficiency in Persuasion and can charm targets after conversation."
          enhancedSenses:
            label: "Enhanced Senses"
            description: "You gain Perception proficiency and superior low-light vision."
          goonBrain:
            label: "Goon Brain"
            description: "Your Intelligence and Wisdom scores are decreased by 1."
          healingFactor:
            label: "Healing Factor"
            description: "You regenerate hit points each round and count as having two fewer exhaustion levels."
          inhumanAppearance:
            label: "Inhuman Appearance"
            description: "Your alien form unsettles others, imposing disadvantage on Persuasion checks."
          inhumanlyLarge:
            label: "Inhumanly Large"
            description: "Your towering size grants advantage on Intimidation but disadvantage on Stealth."
          inefficientMetabolism:
            label: "Inefficient Metabolism"
            description: "You require five times as much food to sustain yourself."
          keenMind:
            label: "Keen Mind"
            description: "You have advantage on Intelligence checks related to memory and puzzles."
          leatheryScales:
            label: "Leathery Scales"
            description: "Your tough hide provides damage reduction and increases your natural armor."
          marfanSyndrome:
            label: "Marfan Syndrome"
            description: "Your limbs are abnormally long and thin, granting advantage on Acrobatics but disadvantage on Athletics."
          martialTraining:
            label: "Martial Training"
            description: "You gain proficiency with all martial weapons and heavy armor."
          menacingMaw:
            label: "Menacing Maw"
            description: "Your powerful bite deals additional damage and can knock foes prone."
          naturalCoder:
            label: "Natural Coder"
            description: "You gain proficiency in a programming-related skill or tool of your choice."
          naturalLeaper:
            label: "Natural Leaper"
            description: "Your jump distances are tripled and you can fall greater heights without harm."
          nematocysts:
            label: "Nematocysts"
            description: "You can deliver a venomous sting once per short rest."
          nocturnalSenses:
            label: "Nocturnal Senses"
            description: "You gain Perception proficiency and dim light doesn’t impose disadvantage."
          OsaLaska:
            label: "OsaLaska"
            description: "A reptilian genome adapted to swamps and rivers. OsaLaskas have keen senses, stealth and adaptability."
          parkourMastery:
            label: "Parkour Mastery"
            description: "You gain Acrobatics proficiency and can move through difficult terrain more easily."
          performanceArtist:
            label: "Performance Artist"
            description: "You gain Performance proficiency and can distract foes with a show."
          pheromones:
            label: "Pheromones"
            description: "Your scent grants advantage on social checks among those who can smell you."
          pounce:
            label: "Pounce"
            description: "You can use Dash, Disengage, or Hide as a bonus action once per rest."
          predatoryForm:
            label: "Predatory Form"
            description: "Your bestial visage imposes disadvantage on foes’ reaction rolls."
          polyglot:
            label: "Polyglot"
            description: "You learn up to four languages for free and gain an Intelligence bonus."
          preyInstincts:
            label: "Prey Instincts"
            description: "You can take Dash, Disengage, or Hide as a free action between rests."
          puppeteer:
            label: "Puppeteer"
            description: "Controllers of daemons and machines, twisting technology to do their bidding."
          reptileBrain:
            label: "Reptile Brain"
            description: "You have advantage on saves against mind-altering effects."
          samurai:
            label: "Samurai"
            description: "Elite mercenaries trained in a code of honor, blending martial skill with corporate loyalty."
          shortLived:
            label: "Short Lived"
            description: "You age twice as fast and die young, but reach maturity early."
          simple:
            label: "Simple"
            description: "Your Intelligence score is decreased by 2."
          simpleMinded:
            label: "Simple Minded"
            description: "You take a penalty to Wisdom and Intelligence checks due to your single-minded focus."
          slumDog:
            label: "Slum Dog"
            description: "You grew up in the undercity, scraping by on the streets and honing your wits to survive in poverty and danger."
          socialChameleon:
            label: "Social Chameleon"
            description: "You can mimic social cues to blend into groups and infiltrate organizations."
          stealthProtocol:
            label: "Stealth Protocol"
            description: "You can become invisible in darkness for a short time."
          stargazer:
            label: "Stargazer"
            description: "You spent nights studying the sky, becoming an expert in navigation, astrology, or the mysteries of the cosmos."
          sturdyFrame:
            label: "Sturdy Frame"
            description: "You gain resistance to bludgeoning damage and your unarmed strikes deal extra damage."
          suit:
            label: "Suit"
            description: "Corporate operatives and negotiators who wield power through influence."
          swiftFeet:
            label: "Swift Feet"
            description: "Difficult terrain doesn’t slow you when dashing, and you don’t provoke opportunity attacks."
          terrifyingForm:
            label: "Terrifying Form"
            description: "Your grotesque appearance grants advantage on Intimidation checks."
          technician:
            label: "Technician"
            description: "You’re a hands-on expert in machines and electronics, skilled at repairing daemons, jury-rigging devices, and hacking hardware."
          tetherUpgradeIntolerant:
            label: "Upgrade Intolerant"
            description: "You suffer a penalty when using or installing cyber or daemon upgrades."
          titan:
            label: "Titan"
            description: "A colossal genome built for unmatched strength. Titans are slow but nearly unbreakable."
          tireless:
            label: "Tireless"
            description: "You always count as two exhaustion levels lower than you actually are."
          toxinResilience:
            label: "Toxin Resilience"
            description: "You have advantage on saving throws against poison and resistance to poison damage."
          traceur:
            label: "Traceur"
            description: "Extreme stunt performers and athletes, blending acrobatics with showmanship."
          trackPrey:
            label: "Track Prey"
            description: "You gain advantage on checks to follow tracks and identify recent passage."
          toughAsNails:
            label: "Tough as Nails"
            description: "Whenever you gain a level, your maximum hit points increase by an additional 2."
          upgradeIntolerant:
            label: "Upgrade Intolerant"
            description: "You suffer a penalty when using or installing cyber or daemon upgrades."
          weak:
            label: "Weak"
            description: "Your Strength score is decreased by 2."
