management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include:
          - "health"
server:
  port: ${SERVER_PORT:0}
spring:
  profiles:
    include:
    - genefunk-crb-locale
    - genefunk-crb
    - h2-database
    - logging
    - rabbitmq
    - oauth