server:
  port: ${SERVER_PORT}
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_USERNAME}
    template:
      reply-timeout: 30000