server:
  port: 8080
logging:
  level:
    com:
      springframework:
        web: DEBUG
        security: DEBUG
        oauth2: DEBUG
        boot: DEBUG
    de:
      hipp:
        pnp:
          auth: debug

spring:
  profiles:
    active: rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
