spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/user;AUTO_SERVER=TRUE
    username: ${USER_DATABASE_USERNAME}
    password: ${USER_DATABASE_PASSWORD}