genefunk:
  books:
    - name: "crb"
      species:
        - name: "Companion"
          description: "companion.description"
          attributes:
            INT: 2
            INT_MAX: 22
            WIS: 2
            WIS_MAX: 22
          features:
            - label: "chemicalDependence.label"
              description: "chemicalDependence.description"
            - label: "enchanting.label"
              description: "enchanting.description"
            - label: "performanceArtist.label"
              description: "performanceArtist.description"
            - label: "pheromones.label"
              description: "pheromones.description"