name: Build and Test with Maven

concurrency:
  group: character-generator-build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-with-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn -B test --file pom.xml

  pipeline-base:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    needs: build-with-tests
    with:
      build_image: character-generator-service
      service_name: character-generator-service
      pom_folder: character-generator-starter
    secrets: inherit

  pipeline-data:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    needs: build-with-tests
    with:
      build_image: data-service
      service_name: data-service
      pom_folder: data-starter
    secrets: inherit

  pipeline-security:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    needs: build-with-tests
    with:
      build_image: security-service
      service_name: security-service
      pom_folder: security-starter
    secrets: inherit

  pipeline-genefunk:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    needs: build-with-tests
    with:
      build_image: genefunk-generator-service
      service_name: genefunk-generator-service
      pom_folder: genefunk-starter
    secrets: inherit
