name: Build Character Generator Starter

on:
  workflow_dispatch:
  push:
    paths:
      - pom.xml
      - api/**
      - base/**
      - character-generator-starter/**

jobs:
  build-and-deploy:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    with:
      build_image: character-generator-service
      service_name: character-generator-service
      pom_folder: character-generator-starter
    secrets: inherit