name: Build Character Generator Starter

on:
  workflow_dispatch:
  push:
    paths:
      - pom.xml
      - api/**
      - base/**
      - character-generator-starter/**

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      project-folder: 'character-generator-starter'
      image-name: 'character-generator-service'
    secrets: inherit