name: Build Character Generator Starter

concurrency:
  group: character-generator-build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - api/**
      - base/**
      - character-generator-starter/**

jobs:
  build-with-tests:

    runs-on: ubuntu-latest
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          access_token_lifetime: 3600s
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn -B test --file character-generator-starter/pom.xml
      - name: Build Image
        run: |
          cd character-generator-starter
          mvn spring-boot:build-image -DskipTests -Pnative -Dimage.build=true -Dimage.push=true -Dimage.name=europe-west3-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY_NAME }}/character-generator-starter:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        id: deploy
        with:
          service: ${{inputs.service_name}}
          image: ${{inputs.registry_hostname}}/${{vars.PROJECT_ID}}/${{vars.REPOSITORY_NAME}}/${{inputs.build_image}}:latest
          region: ${{vars.REGION}}
          flags: '--service-account=${{ secrets.WIF_SERVICE_ACCOUNT }}'
