name: Dependabot Build Verification

# Trigger this workflow on pull requests from dependabot
on:
  pull_request:
    branches: [ main, master, develop ]
    # Only run on dependabot PRs
    paths:
      - 'pom.xml'
      - '**/pom.xml'

jobs:
  build-verification:
    # Only run if the PR is from dependabot
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'corretto'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make mvnw executable
      run: chmod +x ./mvnw
      
    - name: Run Maven verify with update snapshots
      run: ./mvnw verify -U
      
    - name: Comment on PR if build fails
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Build verification failed for this dependabot PR. Please check the logs for details.'
          })
          
    - name: Comment on PR if build succeeds
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Build verification passed! This dependency update is safe to merge.'
          })