name: Build Spring Boot Native Image and deploy it to Cloud Run for live branch

on:
  push:
    branches: [ "live" ]

jobs:


  pipeline-base:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    with:
      build_image: character-generator-service
      service_name: character-generator-service
      pom_folder: starter
    secrets: inherit
