name: Build Spring Boot Native Image and deploy it to Cloud Run for live branch

on:
  push:
    branches: [ "live" ]

jobs:


  pipeline-base:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    with:
      build_image: character-generator-service
      service_name: character-generator-service
      pom_folder: character-generator-starter
    secrets: inherit


  pipeline-data:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    with:
      build_image: data-service
      service_name: data-service
      pom_folder: data-starter
    secrets: inherit

  pipeline-security:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    with:
      build_image: security-service
      service_name: security-service
      pom_folder: security-starter
    secrets: inherit

  pipeline-genefunk:
    uses: Matil86/github-actions/.github/workflows/pipeline-cloud-run-service.yaml@main
    with:
      build_image: genefunk-generator-service
      service_name: genefunk-generator-service
      pom_folder: genefunk-starter
    secrets: inherit
